export const EMPLOYEE_ACTIONS_TYPES = {
  GET_EMPLOYEES_ACTION: 'GET_EMPLOYEES_ACTION',
  GET_EMPLOYEES_FAILED: 'GET_EMPLOYEES_FAILED',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEE_ACTION: 'GET_EMPLOYEE_ACTION',
  GET_EMPLOYEE_FAILED: 'GET_EMPLOYEE_FAILED',
  GET_EMPLOYEE_SUCCESS: 'GET_EMPLOYEE_SUCCESS',
  ADD_EMPLOYEE_ACTION: 'ADD_EMPLOYEE_ACTION',
  ADD_EMPLOYEE_FAILED: 'ADD_EMPLOYEE_FAILED',
  ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
  DELETE_EMPLOYEE_ACTION: 'DELETE_EMPLOYEE_ACTION',
  DELETE_EMPLOYEE_FAILED: 'DELETE_EMPLOYEE_FAILED',
  DELETE_EMPLOYEE_SUCCESS: 'DELETE_EMPLOYEE_SUCCESS',
};
